services:
  - type: web
    name: emotion-ai-ml-service
    env: python
    runtime: python-3.11.9
    rootDir: backend/ml_service
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
